import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Devtter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Devtter</a>
        </h1>
        <nav className={styles.nav}>
          <Link href="/timeline">
            <a>Timeline</a>
          </Link>
        </nav>
      </main>
    </>
  )
}
